### ISSUE TITLE
Unable to use the same codes in google dataproc cluster

### ISSUE THREAD

**Issue by bhargavaganti** [googleapis/java-datacatalog#267]
When i run the sample code in dataproc cluster it throws me an error 

My build.sbt : 

libraryDependencies ++= Seq(
  "org.scala-lang" % "scala-library" % scalaVersion.value % "provided",
  "org.apache.spark" %% "spark-core" % "2.4.0",
  "org.apache.spark" %% "spark-sql" % "2.4.0",
  "org.apache.spark" %% "spark-avro" % "2.4.2",
  "com.amazon.deequ" % "deequ" % "1.0.4",
  "commons-io" % "commons-io" % "2.7",
  "com.google.cloud.spark" %% "spark-bigquery-with-dependencies" % "0.17.1",
  "com.google.cloud" % "google-cloud-datacatalog" % "1.0.1"
)

My dataproc image is Debian10 with spark 2.4

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/api/gax/core/BackgroundResource
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.podium.dataprofiler.PodiumDataProfiler$.main(DataProfiler.scala:63)
	at com.podium.dataprofiler.PodiumDataProfiler.main(DataProfiler.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: com.google.api.gax.core.BackgroundResource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 25 more

**Comment by athakor** [comment]
@bhargavaganti 

 > java.lang.NoClassDefFoundError: com/google/api/gax/core/BackgroundResource 

This is an error that occurs when a particular class is present at compile time, but was missing at run time. To fix this issue you need to create the fat jar using `assemblyShadeRules`.

To create `fat `jar you need to add following shaded rules inside `sbt` config and then run `sbt assembly` command and then submit that jar on `dataproc` cluster.
```javascript
assemblyShadeRules in assembly := Seq(
  ShadeRule
    .rename("com.google.*.**" -> "shade.com.google.shade@1.shade@2")
    .inAll
)
```
